a= int(input ('Unesi prvi broj: '))
b= int (input ('Unesi drugi broj: '))
print("Brojevi su:", a, b)
print("Zbir ova dva broja je:", a+b)
print("Razlika ova dva broja je:", a-b)
print("Proizvod ova dva broja je:", a*b)
print("Ceo broj pri deljenju je:", a//b)
print("Ostatak pri deljenju je:", a%b)
